baseURL = "https://dinz.github.io/BulgarianApp-Fresh/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Bulgarian-German Learning App"
theme = "learn"
metaDataFormat = "yaml"

theme = ["learn"]

[params]
  description = "Learn Bulgarian and German with spaced repetition"
  author = "Bulgarian-German Learning App"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  disableMermaid = true
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "|"
  themeVariant = "auto"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true

[menu]
  [[menu.main]]
    name = 'Vocabulary'
    url = '/vocabulary/'
    weight = 10
  [[menu.main]]
    name = 'Grammar'
    url = '/grammar/'
    weight = 20
  [[menu.main]]
    name = 'Practice'
    url = '/practice/'
    weight = 30

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = 'application/json'
    baseName = 'search-index'
    isPlainText = true
    notAlternative = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
