use crate::{GrammarItem, VocabularyItem};

pub fn vocabulary() -> Vec<VocabularyItem> {
    vec![
    VocabularyItem { word: "Здравей".into(), translation: "Hallo".into(), category: "Begrüßung".into(), level: "A1".into(), notes: Some("Das Wort 'Здравей' leitet sich vom bulgarischen Wort 'здрав' (gesund) ab und ist wie ein Wunsch nach Gesundheit.".into()) },
    VocabularyItem { word: "Добро утро".into(), translation: "Guten Morgen".into(), category: "Begrüßung".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Добър ден".into(), translation: "Guten Tag".into(), category: "Begrüßung".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Добър вечер".into(), translation: "Guten Abend".into(), category: "Begrüßung".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Лека нощ".into(), translation: "Gute Nacht".into(), category: "Begrüßung".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Довиждане".into(), translation: "Auf Wiedersehen".into(), category: "Begrüßung".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Моля".into(), translation: "Bitte".into(), category: "Ausdruck".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Благодаря".into(), translation: "Danke".into(), category: "Ausdruck".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Извинете".into(), translation: "Entschuldigung".into(), category: "Ausdruck".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Съжалявам".into(), translation: "Es tut mir leid".into(), category: "Ausdruck".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Човек".into(), translation: "Mensch".into(), category: "Substantiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Семейство".into(), translation: "Familie".into(), category: "Substantiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Къща".into(), translation: "Haus".into(), category: "Substantiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Училище".into(), translation: "Schule".into(), category: "Substantiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Работа".into(), translation: "Arbeit".into(), category: "Substantiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Град".into(), translation: "Stadt".into(), category: "Substantiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Село".into(), translation: "Dorf".into(), category: "Substantiv".into(), level: "A1".into(), notes: Some("'Село' bedeutet Dorf und ist mit anderen slawischen Wörtern für Siedlung verwandt.".into()) },
    VocabularyItem { word: "Книга".into(), translation: "Buch".into(), category: "Substantiv".into(), level: "A1".into(), notes: Some("'Книга' stammt aus dem Altslawischen und war ursprünglich eine Bezeichnung für eine Schriftrolle oder ein gebundenes Werk.".into()) },
    VocabularyItem { word: "Храна".into(), translation: "Essen".into(), category: "Substantiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Вода".into(), translation: "Wasser".into(), category: "Substantiv".into(), level: "A1".into(), notes: Some("'Вода' ist Wasser und hat denselben indoeuropäischen Ursprung wie das deutsche 'Wasser'.".into()) },
    VocabularyItem { word: "Съм".into(), translation: "sein".into(), category: "Verb".into(), level: "A1".into(), notes: Some("Das Verb 'съм' entspricht dem deutschen 'sein' und ist unregelmäßig.".into()) },
    VocabularyItem { word: "Имам".into(), translation: "haben".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Правя".into(), translation: "machen".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Мога".into(), translation: "können".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Ходя".into(), translation: "gehen".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Ям".into(), translation: "essen".into(), category: "Verb".into(), level: "A1".into(), notes: Some("'Ям' ist ein kurzes Verb, das 'essen' bedeutet; es gehört zu den Grundverben wie im Deutschen 'essen'.".into()) },
    VocabularyItem { word: "Пия".into(), translation: "trinken".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Говоря".into(), translation: "sprechen".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Виждам".into(), translation: "sehen".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Чувам".into(), translation: "hören".into(), category: "Verb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Добър".into(), translation: "gut".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Лош".into(), translation: "schlecht".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Голям".into(), translation: "groß".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Малък".into(), translation: "klein".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Нов".into(), translation: "neu".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Стар".into(), translation: "alt".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Красив".into(), translation: "schön".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Грозен".into(), translation: "hässlich".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Топъл".into(), translation: "warm".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Студен".into(), translation: "kalt".into(), category: "Adjektiv".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Тук".into(), translation: "hier".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Там".into(), translation: "dort".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Сега".into(), translation: "jetzt".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Тогава".into(), translation: "dann".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Бързо".into(), translation: "schnell".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Бавно".into(), translation: "langsam".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Често".into(), translation: "oft".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Редко".into(), translation: "selten".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Добре".into(), translation: "gut".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Зле".into(), translation: "schlecht".into(), category: "Adverb".into(), level: "A1".into(), notes: None },
    VocabularyItem { word: "Маса".into(), translation: "Tisch".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Стол".into(), translation: "Stuhl".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Хладилник".into(), translation: "Kühlschrank".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Кухня".into(), translation: "Küche".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Апартамент".into(), translation: "Wohnung".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Автомобил".into(), translation: "Auto".into(), category: "Substantiv".into(), level: "A2".into(), notes: Some("'Автомобил' ist ein Lehnwort aus dem Französischen; es setzt sich aus 'auto' (selbst) und 'mobile' (beweglich) zusammen.".into()) },
    VocabularyItem { word: "Магазин".into(), translation: "Laden".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Градина".into(), translation: "Garten".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Часовник".into(), translation: "Uhr".into(), category: "Substantiv".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Чета".into(), translation: "lesen".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Пиша".into(), translation: "schreiben".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Карам".into(), translation: "fahren".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Живея".into(), translation: "leben".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Работя".into(), translation: "arbeiten".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Уча".into(), translation: "lernen".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Едно".into(), translation: "eins".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Две".into(), translation: "zwei".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Три".into(), translation: "drei".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Четири".into(), translation: "vier".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Пет".into(), translation: "fünf".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Шест".into(), translation: "sechs".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Седем".into(), translation: "sieben".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Осем".into(), translation: "acht".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Девет".into(), translation: "neun".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Десет".into(), translation: "zehn".into(), category: "Zahl".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Много".into(), translation: "viele".into(), category: "Quantor".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Малко".into(), translation: "wenig".into(), category: "Quantor".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Всички".into(), translation: "alle".into(), category: "Quantor".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Няколко".into(), translation: "einige".into(), category: "Quantor".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Никой".into(), translation: "keiner".into(), category: "Quantor".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Понеделник".into(), translation: "Montag".into(), category: "Tag".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Вторник".into(), translation: "Dienstag".into(), category: "Tag".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Сряда".into(), translation: "Mittwoch".into(), category: "Tag".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Четвъртък".into(), translation: "Donnerstag".into(), category: "Tag".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Петък".into(), translation: "Freitag".into(), category: "Tag".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Събота".into(), translation: "Samstag".into(), category: "Tag".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Неделя".into(), translation: "Sonntag".into(), category: "Tag".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Час".into(), translation: "Stunde".into(), category: "Zeit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Минута".into(), translation: "Minute".into(), category: "Zeit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Сутрин".into(), translation: "Morgen".into(), category: "Zeit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Обед".into(), translation: "Mittag".into(), category: "Zeit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Следобед".into(), translation: "Nachmittag".into(), category: "Zeit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Вечер".into(), translation: "Abend".into(), category: "Zeit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Нощ".into(), translation: "Nacht".into(), category: "Zeit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Как си?".into(), translation: "Wie geht's?".into(), category: "Ausdruck".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Добре съм".into(), translation: "Mir geht's gut".into(), category: "Ausdruck".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Извинявай".into(), translation: "Entschuldige".into(), category: "Ausdruck".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Може ли?".into(), translation: "Darf ich?".into(), category: "Ausdruck".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Хляб".into(), translation: "Brot".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Мляко".into(), translation: "Milch".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Сирене".into(), translation: "Käse".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Месо".into(), translation: "Fleisch".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Риба".into(), translation: "Fisch".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Зеленчуци".into(), translation: "Gemüse".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Плодове".into(), translation: "Obst".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Сок".into(), translation: "Saft".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Кафе".into(), translation: "Kaffee".into(), category: "Lebensmittel".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Автобус".into(), translation: "Bus".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Влак".into(), translation: "Zug".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Самолет".into(), translation: "Flugzeug".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Такси".into(), translation: "Taxi".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Гара".into(), translation: "Bahnhof".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Летище".into(), translation: "Flughafen".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Хотел".into(), translation: "Hotel".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Билет".into(), translation: "Ticket".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Път".into(), translation: "Straße".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Карта".into(), translation: "Karte".into(), category: "Transport".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Лекар".into(), translation: "Arzt".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Болница".into(), translation: "Krankenhaus".into(), category: "Gesundheit".into(), level: "A2".into(), notes: Some("'Болница' leitet sich von 'болен' (krank) ab und bezeichnet einen Ort für Kranke – wie das deutsche 'Krankenhaus'.".into()) },
    VocabularyItem { word: "Аптека".into(), translation: "Apotheke".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Лекарства".into(), translation: "Medikamente".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Спешно".into(), translation: "Notfall".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Болка".into(), translation: "Schmerz".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Здраве".into(), translation: "Gesundheit".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Треска".into(), translation: "Fieber".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Настинка".into(), translation: "Erkältung".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Помощ".into(), translation: "Hilfe".into(), category: "Gesundheit".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Слънце".into(), translation: "Sonne".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Дъжд".into(), translation: "Regen".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Сняг".into(), translation: "Schnee".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Вятър".into(), translation: "Wind".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Температура".into(), translation: "Temperatur".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Облаци".into(), translation: "Wolken".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Гора".into(), translation: "Wald".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Река".into(), translation: "Fluss".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Планина".into(), translation: "Berg".into(), category: "Natur".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Море".into(), translation: "Meer".into(), category: "Natur".into(), level: "A2".into(), notes: Some("'Море' bedeutet Meer und ist mit dem russischen 'more' verwandt; es geht auf eine urslawische Wurzel zurück.".into()) },
    VocabularyItem { word: "Майка".into(), translation: "Mutter".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Баща".into(), translation: "Vater".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Брат".into(), translation: "Bruder".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Сестра".into(), translation: "Schwester".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Съпруг".into(), translation: "Ehemann".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Съпруга".into(), translation: "Ehefrau".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Дете".into(), translation: "Kind".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Приятел".into(), translation: "Freund".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Приятелка".into(), translation: "Freundin".into(), category: "Familie".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Пари".into(), translation: "Geld".into(), category: "Einkauf".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Цена".into(), translation: "Preis".into(), category: "Einkauf".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Евро".into(), translation: "Euro".into(), category: "Einkauf".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Лев".into(), translation: "Lew".into(), category: "Einkauf".into(), level: "A2".into(), notes: Some("Die bulgarische Währung 'лев' ist nach dem alten bulgarischen Wort für 'Löwe' benannt, weil der Löwe ein nationales Symbol ist.".into()) },
    VocabularyItem { word: "Сметка".into(), translation: "Rechnung".into(), category: "Einkauf".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Касова бележка".into(), translation: "Quittung".into(), category: "Einkauf".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Отстъпка".into(), translation: "Rabatt".into(), category: "Einkauf".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Купувам".into(), translation: "kaufen".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Продавам".into(), translation: "verkaufen".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    VocabularyItem { word: "Пазарувам".into(), translation: "einkaufen".into(), category: "Verb".into(), level: "A2".into(), notes: None },
    ]
}

pub fn grammar() -> Vec<GrammarItem> {
    vec![
    GrammarItem { title: "Word Order".into(), description: "Bulgarian word order is flexible thanks to subject–verb agreement.
The neutral pattern is S + V + O + A (Subject, Verb, Object, Adjunct), but other orders such as A + S + V + O, O + S + V + A or S + V + A + O are also possible.
You can change the order to emphasise different parts of the sentence without changing the basic meaning.".into(), examples: vec!["Той видя момичето в далечината. – He saw the girl in the distance.".to_string(), "В далечината той видя момичето. – In the distance, he saw the girl.".to_string(), "Момичето той видя в далечината. – The girl he saw in the distance.".to_string()], level: "A1".into() },
    GrammarItem { title: "Gender of Nouns".into(), description: "Bulgarian nouns have three grammatical genders: masculine, feminine and neuter.
Masculine nouns usually end in a consonant (мъж – man, син – son).
Feminine nouns often end in –а/–я (жена – woman, ябълка – apple).
Neuter nouns typically end in –е/–о (море – sea, месо – meat).
There are exceptions: some masculine nouns end in –а/–я (баща – father), some feminine nouns end in a consonant (любов – love), and some neuter nouns end in –и or –ю (такси – taxi).".into(), examples: vec!["мъж – man (masculine)".to_string(), "жена – woman (feminine)".to_string(), "море – sea (neuter)".to_string(), "баща – father (masculine ending in –а)".to_string(), "любов – love (feminine ending in consonant)".to_string()], level: "A1".into() },
    GrammarItem { title: "Singular and Plural".into(), description: "Bulgarian nouns are either singular or plural.
Masculine nouns form plurals with endings like –и, –е or –ове (стол – столове 'chair – chairs').
Feminine nouns replace –а/–я with –и (жена – жени 'woman – women').
Neuter nouns take –а or –ета (море – морета 'sea – seas').
A historical dual number for pairs of inanimate masculine nouns survives with the ending –а (два стола – two chairs).".into(), examples: vec!["стол – столове (chair – chairs)".to_string(), "жена – жени (woman – women)".to_string(), "море – морета (sea – seas)".to_string(), "два стол а (two chairs – dual form)".to_string()], level: "A1".into() },
    GrammarItem { title: "Definite Article".into(), description: "The Bulgarian definite article attaches to the end of the noun.
Masculine nouns take –ът/–ят (студент – студентът 'the student', кон – конят 'the horse').
Feminine nouns take –та (вода – водата 'the water', чиния – чинията 'the plate').
Neuter nouns take –то (село – селото 'the village', море – морето 'the sea').
For plural nouns the article is –те for masculine and feminine plurals and –та for neuter plurals.".into(), examples: vec!["студент – студентът (student – the student)".to_string(), "вода – водата (water – the water)".to_string(), "село – селото (village – the village)".to_string(), "мъже – мъжете (men – the men)".to_string()], level: "A1".into() },
    GrammarItem { title: "Pronouns and Cases".into(), description: "Bulgarian cases exist mainly in personal pronouns.
There are three cases: nominative (аз, ти, той, тя, то, ние, вие, те), accusative (ме, те, го, я, го, ни, ви, ги) and dative (ми, ти, му, й, му, ни, ви, им).
Use the nominative for subjects, the accusative for direct objects and the dative for indirect objects.".into(), examples: vec!["Аз го попитах как се чувства. – I asked him how he was feeling. (go – accusative)".to_string(), "Аз му дадох моята книга. – I gave my book to him. (mu – dative)".to_string()], level: "A1".into() },
    GrammarItem { title: "Present and Future Tenses".into(), description: "Bulgarian verbs conjugate for person and number.
The present tense expresses ongoing actions (Аз уча български – I study Bulgarian).
Future tense uses the particle ще and the present tense of the verb (Аз ще уча български – I will study Bulgarian).".into(), examples: vec!["Аз уча български. – I study Bulgarian.".to_string(), "Аз ще уча български. – I will study Bulgarian.".to_string()], level: "A1".into() },
    GrammarItem { title: "Past Tenses".into(), description: "For A2 learners it's useful to distinguish between the past aorist and the past imperfect.
The past aorist describes completed actions (Аз учих български – I studied Bulgarian), while the past imperfect describes continuous or habitual past actions (Аз учех български – I was studying Bulgarian).".into(), examples: vec!["Аз учих български. – I studied Bulgarian.".to_string(), "Аз учех български. – I was studying Bulgarian.".to_string()], level: "A2".into() },
    GrammarItem { title: "Quantifiers and Numbers".into(), description: "At level A2 you'll encounter quantifiers and numbers more frequently.
The words много (many/much), малко (few/little), всички (all), няколко (several) and никой (none) help quantify nouns.
Bulgarian numbers one through ten are: едно, две, три, четири, пет, шест, седем, осем, девет, десет.".into(), examples: vec!["Имам много книги. – I have many books.".to_string(), "Имаме няколко стола. – We have several chairs.".to_string()], level: "A2".into() },
    GrammarItem { title: "Time Expressions".into(), description: "Talking about time requires vocabulary for days and parts of the day.
The days of the week are понеделник, вторник, сряда, четвъртък, петък, събота and неделя.
Parts of the day include сутрин (morning), обед (noon), следобед (afternoon), вечер (evening) and нощ (night).".into(), examples: vec!["Срещаме се във вторник сутрин. – We meet on Tuesday morning.".to_string(), "Работя всеки ден следобед. – I work every afternoon.".to_string()], level: "A2".into() },
    GrammarItem { title: "Food and Shopping Vocabulary".into(), description: "Food and shopping conversations are frequent at A2.
Learn common nouns for food (хляб – bread, мляко – milk, сирене – cheese) and verbs for shopping (купувам – to buy, продавам – to sell, пазарувам – to shop).
Understanding basic currency words like лев (the Bulgarian currency) and евро (euro) is also helpful.".into(), examples: vec!["Купувам хляб от магазина. – I buy bread from the shop.".to_string(), "Колко струва това? – How much does this cost?".to_string()], level: "A2".into() },
    GrammarItem { title: "Travel and Directions".into(), description: "At A2 you may need to ask for directions or discuss travel.
Key nouns include автобус (bus), влак (train), самолет (airplane), такси (taxi), гара (train station) and летище (airport).
The noun билет means 'ticket', and карта means 'map'.".into(), examples: vec!["Къде е гарата? – Where is the train station?".to_string(), "Имам билет за автобуса. – I have a ticket for the bus.".to_string()], level: "A2".into() },
    ]
}
